#config_version=6

#secret high hopes mode. hit the 3 division bell standup targets twice
#each in order. ie...target 1, target 1, target 2, target 2, target 3,
#target 3 in order to immediately launch secret mode. shoot lit ramps and 
#orbits for increasing jackpots.

mode:
  start_events: start_high_hopes
  stop_events: stop_high_hopes
  priority: 200