#config_version=6

#high score mode.

mode:
  priority: 500
  start_events: game_ending, start_high_score
  use_wait_queue: true

high_score:
  categories: !!omap
  - score:
    - GRAND CHAMPION
    - HIGH SCORE 1
    - HIGH SCORE 2
    - HIGH SCORE 3
    - HIGH SCORE 4

slide_player:
  _overwrite: true
  high_score_enter_initials: high_score_enter_initials
  high_score_award_display: high_score_award_display