#config_version=6
#attract mode config file


mode_settings:
  selectable_items:
    - title
    - credits
  next_item_events: s_right_flipper_active
  previous_item_events: s_left_flipper_active

slide_player:
  mode_attract_started: attract

sound_player:
  mode_attract_started:
    welcome_to_the_machine:
      bus: music
