#config_version=6
#attract mode config file


slide_player:
  mode_attract_started: attract

  mode_attract_stopping:
    attract:
      action: remove
      
event_player:
  s_rght_flipper_active: right_full
  s_right_flipper_inactive: right_rest
  mode_mode_select_carousel_started: move_to_0
