#config_version=6
#base mode config file
mode:
  start_events: ball_starting
  priority: 100
 
slide_player:
  mode_base_started: base
 
#sound_player:
# mode_base_started:
#   base_radio:
#     bus: music
#  resume_base_radio:
#    base_radio:
#      bus: music
 
variable_player:
  #rollovers
  s_left_inlane_active:
    score: 100
  s_left_outlane_active:
    score: 100
  s_right_inlane_active:
    score: 100
  s_right_outlane_active:
    score: 100
  s_left_upper_ro_active:
    score: 100
  s_right_upper_ro_active:
    score: 100
  #spinners
  s_left_spinner_active:
    score: 100
  s_right_spinner_active:
    score: 100
  s_left_hs_spinner_active:
    score: 100
  s_right_hs_spinner_active:
    score: 100
  #standups
  s_a_active:
    score: 500
  s_n_active:
    score: 500
  s_i_active:
    score: 500
  s_m_active:
    score: 500
  s_aa_active:
    score: 500
  s_l_active:
    score: 500
  s_s_active:
    score: 500
  s_db_1_active:
    score: 500
  s_db_2_active:
    score: 500
  s_db_3_active:
    score: 500
  #drops
  s_wall_top_right_active:
    score: 1000
  s_wall_top_center_active:
    score: 1000
  s_wall_top_left_active:
    score: 1000
  s_wall_bottom_right_active:
    score: 1000
  s_wall_bottom_center_active:
    score: 1000
  s_wall_bottom_left_active:
    score: 1000
  #bumpers
  s_pop_1_active:
    score: 500
  s_pop_2_active:
    score: 500
  #slings
  s_sling_left_active:
    score: 100
  s_sling_right_active:
    score: 100
  #hammer
  s_subway_opto_active:
    score: 3000
  #vuk
  s_vuk_opto_active:
    score: 5000
 
  # --- BIKE INLANE QUALIFY (player var method) ---
  "s_left_inlane_active{current_player.active_main_mode == 'inactive' and current_player.pending_mode == 'inactive'}":
    bike_left_inlane_hit:
      action: set
      int: 1
 
  "s_right_inlane_active{current_player.active_main_mode == 'inactive' and current_player.pending_mode == 'inactive'}":
    bike_right_inlane_hit:
      action: set
      int: 1
 
  mode_bike_started:
    bike_left_inlane_hit:
      action: set
      int: 0
    bike_right_inlane_hit:
      action: set
      int: 0
 
event_player:
  "player_bike_left_inlane_hit{current_player.bike_right_inlane_hit == 1 and current_player.pending_mode == 'inactive'}": start_bike
  "player_bike_right_inlane_hit{current_player.bike_left_inlane_hit == 1 and current_player.pending_mode == 'inactive'}": start_bike
 
  mode_bike_stopped: resume_base_radio
  wall_mode_completed: resume_base_radio
 
# REMOVED: shots, shot_groups blocks
