#config_version=6

#multiball mode. underfined at the moment. probably gonna use white wood #3
#additions such as newton ball and or ball lock.

mode:
  start_events: start_multiball
  stop_events: stop_multiball
  priority: 200