#config_version=6


#  devices/coils.yaml
#  ----------------------
#  FAST BOARDS
#  Neuron
#  IO 0024 CABINET IO BOARD
#  IO 3208 LOWER THIRD IO BOARD
#  IO 1616 UPPER PLAYFIELD IO BOARD

coils:

#  -----  IO 0024  :  cabinet drivers  -----

#  -----  IO 3208  :  bottom third drivers  -----

#trough

  #c_trough_eject_coil:
    #number: 3208-0
    #default_pulse_ms: 15

#slings

  c_right_sling:
    number: 3208-1
    default_pulse_ms: 25

  c_left_sling:
    number: 3208-2
    default_pulse_ms: 25

  c_auto_plunger:
    number: 3208-3
    default_pulse_ms: 15

#flippers

  c_flipper_right_main:
    number: 3208-4
    default_pulse_ms: 30

  c_flipper_right_hold:
    number: 3208-5
    default_hold_power: .125
    allow_enable: true

  c_flipper_left_main:
    number: 3208-6
    default_pulse_ms: 30

  c_flipper_left_hold:
    number: 3208-7
    default_hold_power: .125
    allow_enable: true

#  -----  IO 1616  :  upper playfield drivers  -----

autofire_coils:

  slingshot_left:
    coil: c_left_sling
    switch: s_left_sling
    enable_events: machine_reset_phase_3

  slingshot_right:
    coil: c_right_sling
    switch: s_right_sling
    enable_events: machine_reset_phase_3

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
    enable_events: machine_reset_phase_3

  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper
    enable_events: machine_reset_phase_3
