#config_version=6

#division bell mode. hit pop bumbers 100 times. start 60 second timer to shoot
#vuk. succesful vuk shot starts mode. upper appearing posts pop up depending on
#orbit spinner hit to direct ball to pop bumpers. hit pop bumbers 20 more times
#within 60 seconds to complete mode.

mode:
  start_events: start_division_bell
  stop_events: stop_division_bell
  priority: 200