#config_version=6

#animals mode. hit the 7 standup targets, then 60 seconds to hit the vuk to 
#activate the mode. if mode is activated, hit both of the center playfield drop
#targets 3 times to complete the mode. if mode is not started within the 60 second
#time limit then all 7 targets reset.

mode:
  start_events: start_animals
  stop_events: stop_animals
  priority: 200